plugins:
  texdem_events_enabled:
    default: true
    client: false

  texdem_events_limit:
    default: 100
    client: false

  texdem_google_maps_api_key:
    default: ""
    client: false
    secret: true
